"""L3 tool — render the final ``TestPlanDocument`` and write run artifacts.

The deterministic half of the output (metadata header, the authoritative gaps
table, the Human Review Gate) is generated here so it can never be forgotten
or hallucinated by the model. The LLM only supplies the plan body (rule R2, R6).
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = PROJECT_ROOT / "runs"

DRAFT_BANNER = "**STATUS: DRAFT — awaiting human review.**"
_UNSAFE = re.compile(r"[^A-Za-z0-9._-]+")


def _sanitize(value: str) -> str:
    """Make a value safe to use as a filename component."""
    cleaned = _UNSAFE.sub("-", value).strip("-")
    return cleaned or "ticket"


def build_document(
    ticket: Dict[str, Any],
    gaps: List[Dict[str, str]],
    draft_body: str,
    model: str,
    duration_seconds: float = 0.0,
) -> Dict[str, Any]:
    """Assemble the ``TestPlanDocument`` defined in ``llm.md`` §3.4."""
    criteria = ticket.get("acceptance_criteria") or []
    sources = sorted({item.get("source", "") for item in criteria if item.get("source")})
    scenarios = _count_scenarios(draft_body)

    return {
        "jira_key": ticket.get("key", ""),
        "title": ticket.get("summary", ""),
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "status": "draft",  # never "final" (rule R2)
        "model": model,
        "duration_seconds": round(duration_seconds, 1),
        "source_url": ticket.get("source_url", ""),
        "issue": {
            "type": ticket.get("type", ""),
            "status": ticket.get("status", ""),
            "priority": ticket.get("priority", ""),
            "components": ticket.get("components", []),
            "labels": ticket.get("labels", []),
            "fixVersions": ticket.get("fixVersions", []),
        },
        "acceptance_criteria": criteria,
        "acceptance_criteria_sources": sources,
        "gaps": gaps,
        "scenario_count": scenarios,
        "draft_body": draft_body,
        "review_gate": {
            "pending": True,
            "open_questions": [gap["question"] for gap in gaps],
            "summary": (
                f"{len(gaps)} open question(s) must be answered by the ticket author "
                "before this plan can be signed off."
                if gaps
                else "No blocking questions were detected, but human sign-off is still required."
            ),
        },
    }


def _count_scenarios(draft_body: str) -> int:
    """Count scenario rows in the draft, for the UI summary."""
    matches = re.findall(r"\bTS-\d+\b", draft_body)
    if matches:
        return len(set(matches))
    table_rows = re.findall(r"^\|\s*(?!Scenario|\s*---)[^|]+\|", draft_body, re.MULTILINE)
    return len(table_rows)


def render_markdown(document: Dict[str, Any]) -> str:
    """Render the document as the final Markdown artifact."""
    issue = document.get("issue", {})
    criteria = document.get("acceptance_criteria") or []
    gaps = document.get("gaps") or []

    def joined(values: List[str]) -> str:
        return ", ".join(values) if values else "—"

    lines: List[str] = [
        f"# Test Plan — {document['jira_key']}: {document['title']}",
        "",
        f"> {DRAFT_BANNER}",
        f">",
        f"> Generated by the Test Plan Agent (B.L.A.S.T.) on {document['generated_at']} "
        f"using local model `{document['model']}`.",
        f"> A human owns sign-off: this plan is **not final** and must not be treated as approved.",
        "",
        "## Document Information",
        "",
        "| Field | Details |",
        "|---|---|",
        f"| Jira Key | `{document['jira_key']}` |",
        f"| Summary | {document['title']} |",
        f"| Issue Type | {issue.get('type') or '—'} |",
        f"| Jira Status | {issue.get('status') or '—'} |",
        f"| Priority | {issue.get('priority') or '—'} |",
        f"| Components | {joined(issue.get('components') or [])} |",
        f"| Labels | {joined(issue.get('labels') or [])} |",
        f"| Fix Versions | {joined(issue.get('fixVersions') or [])} |",
        f"| Source | {document.get('source_url') or '—'} |",
        f"| Model | `{document['model']}` |",
        f"| Generated | {document['generated_at']} |",
        f"| Acceptance Criteria Found | {len(criteria)} |",
        f"| Acceptance Criteria Sources | {joined(document.get('acceptance_criteria_sources') or [])} |",
        f"| Scenarios Drafted | {document.get('scenario_count', 0)} |",
        f"| Open Questions | {len(gaps)} |",
        f"| Document Status | Draft |",
        "",
        "---",
        "",
    ]

    if criteria:
        lines.extend(["## Acceptance Criteria (as fetched from Jira)", ""])
        lines.extend(
            f"- **{item['id']}** _(source: {item.get('source', 'unknown')})_ — {item['text']}"
            for item in criteria
        )
        lines.extend(["", "---", ""])
    else:
        lines.extend(
            [
                "## Acceptance Criteria (as fetched from Jira)",
                "",
                "> **None found.** No acceptance criteria exist in the configured custom field, the "
                "description, or the comments. Nothing has been invented to fill the gap — see "
                "Gaps & Questions below.",
                "",
                "---",
                "",
            ]
        )

    lines.extend([document.get("draft_body", "").strip(), "", "---", ""])

    # Authoritative gaps section (deterministic — not model-generated).
    lines.extend(["## Gaps & Questions for the author", ""])
    if gaps:
        lines.extend(
            [
                "Every row below is a checklist item the ticket does not state, or states "
                "ambiguously. These are the questions to resolve before sign-off.",
                "",
                "| id | Category | Status | Checklist item | Evidence | Question |",
                "|---|---|---|---|---|---|",
            ]
        )
        for gap in gaps:
            evidence = str(gap.get("evidence", "")).replace("|", "\\|")
            question = str(gap.get("question", "")).replace("|", "\\|")
            item = str(gap.get("checklist_item", "")).replace("|", "\\|")
            lines.append(
                f"| {gap['id']} | {gap['category']} | {gap['status']} | {item} | {evidence} | {question} |"
            )
    else:
        lines.append("No gaps detected — every checklist item has evidence in the ticket.")
    lines.extend(["", "---", ""])

    lines.extend(
        [
            "## Human Review Gate",
            "",
            f"- **Assumptions made:** the ticket text above is complete and current as of "
            f"`{document['generated_at']}`.",
            f"- **Open questions:** {len(gaps)} — listed in *Gaps & Questions for the author*.",
            "- **Traceability:** each scenario is tagged with the `AC-*` or `GAP-*` ids it covers.",
            "- **This plan is not final.** Review, edit, and approve it before it drives execution.",
            "- No credentials or personal information from the ticket are reproduced in this artifact.",
            "",
            "---",
            "",
            "*Generated by Test Plan Agent — reads Jira, drafts with a local LLM, and always stops "
            "for human review.*",
            "",
        ]
    )

    return "\n".join(lines)


def write_artifacts(document: Dict[str, Any], markdown: str) -> Dict[str, str]:
    """Write the Markdown + JSON artifacts into ``runs/`` and return their paths."""
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    stem = f"{_sanitize(document['jira_key'])}-test-plan-{stamp}"

    md_path = RUNS_DIR / f"{stem}.md"
    json_path = RUNS_DIR / f"{stem}.json"

    md_path.write_text(markdown, encoding="utf-8")
    json_path.write_text(json.dumps(document, indent=2, ensure_ascii=False), encoding="utf-8")

    return {
        "markdown_name": md_path.name,
        "json_name": json_path.name,
        "markdown_path": str(md_path),
        "json_path": str(json_path),
    }


def render_and_write(document: Dict[str, Any]) -> Tuple[str, Dict[str, str]]:
    """Render the Markdown and persist both artifacts."""
    markdown = render_markdown(document)
    return markdown, write_artifacts(document, markdown)
